INSERT INTO roles(name) VALUES('ROLE_USER');
INSERT INTO roles(name) VALUES('ROLE_RESPO');

INSERT INTO roles(name) VALUES('ROLE_RESP_STAGE');
INSERT INTO roles(name) VALUES('ROLE_RESP_RECRUT');
INSERT INTO roles(name) VALUES('ROLE_RESP_EVEN');